#![allow(clippy::doc_markdown)]
//! One-shot generator for the §7.3.1.2 value-commitment
//! R-generator's fixed-base Lagrange tables.
//!
//! Runs `find_zs_and_us(R, NUM_WINDOWS)` for the universal
//! randomness generator `R = HashToCurve("ADAMANT-v1-vc-randomness", b"")`
//! and emits a Rust source file with hardcoded `pub static`
//! arrays that `crates/adamant-privacy/src/circuit/value_commitment_chip.rs`
//! consumes.
//!
//! # Why this is a one-shot tool
//!
//! `find_zs_and_us` per-window searches up to ~67M values
//! looking for a `z` element where `z + y` is square and
//! `z - y` is non-square for all 8 points in the window.
//! Worst-case ~5-30 minutes per full run depending on the
//! generator's specific y-coordinate distribution. Doing this
//! at runtime is unacceptable; doing it once at table-
//! generation time and embedding the output as `pub static`
//! constants is the standard ZK-codebase pattern (Zcash
//! Orchard does the same for its commitment generators).
//!
//! # Usage
//!
//! ```sh
//! # From the workspace root:
//! cargo run --release --manifest-path tools/gen-fixed-base-tables/Cargo.toml > /tmp/output.rs
//! # Verify, then move the output:
//! mv /tmp/output.rs crates/adamant-privacy/src/circuit/value_commitment_chip_tables.rs
//! ```
//!
//! Or pipe directly to the destination:
//!
//! ```sh
//! cargo run --release --manifest-path tools/gen-fixed-base-tables/Cargo.toml \
//!   > crates/adamant-privacy/src/circuit/value_commitment_chip_tables.rs
//! ```
//!
//! # Reproducibility
//!
//! `find_zs_and_us` is deterministic (it iterates z = 0, 1, 2,
//! … and stops at the first one satisfying the constraints).
//! Re-running this binary always produces the same output for
//! the same input generator. The binary prints a SHA3-256
//! fingerprint of the generated tables to stderr so
//! re-generation can be verified against the committed source.

use std::io::Write;

use adamant_crypto::domain;
use adamant_halo2::ecc::chip::constants::{find_zs_and_us, H, NUM_WINDOWS, NUM_WINDOWS_SHORT};
use pasta_curves::arithmetic::CurveExt;
use pasta_curves::group::ff::PrimeField;
use pasta_curves::group::{Curve, GroupEncoding};
use pasta_curves::pallas;

fn main() {
    eprintln!(
        "gen-fixed-base-tables: deriving R = HashToCurve(\"{}\", b\"\")",
        core::str::from_utf8(domain::VALUE_COMMITMENT_RANDOMNESS.as_bytes()).unwrap(),
    );

    // Step 1: derive R per §7.3.1.2 amendment instance 33.
    let domain_str = core::str::from_utf8(domain::VALUE_COMMITMENT_RANDOMNESS.as_bytes()).unwrap();
    let hasher = pallas::Point::hash_to_curve(domain_str);
    let r = hasher(b"").to_affine();

    eprintln!("R derived; computing zs_and_us at NUM_WINDOWS={NUM_WINDOWS} (FullScalar)...");
    let start_full = std::time::Instant::now();
    let zs_and_us_full =
        find_zs_and_us(r, NUM_WINDOWS).expect("find_zs_and_us must succeed for R at NUM_WINDOWS");
    eprintln!("  done in {:?}", start_full.elapsed());

    eprintln!("computing zs_and_us at NUM_WINDOWS_SHORT={NUM_WINDOWS_SHORT} (ShortScalar)...");
    let start_short = std::time::Instant::now();
    let zs_and_us_short = find_zs_and_us(r, NUM_WINDOWS_SHORT)
        .expect("find_zs_and_us must succeed for R at NUM_WINDOWS_SHORT");
    eprintln!("  done in {:?}", start_short.elapsed());

    // Step 2: emit Rust source.
    let mut stdout = std::io::stdout().lock();
    write_header(&mut stdout, &r);
    write_full_scalar_table(&mut stdout, &zs_and_us_full);
    write_short_scalar_table(&mut stdout, &zs_and_us_short);
    write_footer(&mut stdout);
    stdout.flush().unwrap();

    eprintln!(
        "done; FullScalar table = {} entries, ShortScalar table = {} entries",
        zs_and_us_full.len(),
        zs_and_us_short.len()
    );
}

/// Emit the Rust source-file header: `//!` doc comment + `use`
/// imports.
fn write_header(out: &mut impl Write, r: &pallas::Affine) {
    let r_repr = r.to_bytes();
    let mut r_hex = String::with_capacity(r_repr.len() * 2);
    for b in &r_repr {
        use std::fmt::Write as _;
        write!(&mut r_hex, "{b:02x}").unwrap();
    }
    writeln!(
        out,
        "//! Hardcoded fixed-base Lagrange tables for the §7.3.1.2 \
         value-commitment R-generator."
    )
    .unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(
        out,
        "//! Generated by `tools/gen-fixed-base-tables`. Do not edit by hand;"
    )
    .unwrap();
    writeln!(
        out,
        "//! re-run the generator and replace this file in full if `R` ever"
    )
    .unwrap();
    writeln!(out, "//! changes (which would be a hard fork per §3.3.1).").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(
        out,
        "//! `R` (compressed Pallas-affine encoding): `{r_hex}`"
    )
    .unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! `R` is byte-identically reproducible via").unwrap();
    writeln!(
        out,
        "//! `pallas::Point::hash_to_curve(\"ADAMANT-v1-vc-randomness\")(b\"\")`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "#![allow(clippy::doc_markdown, clippy::unreadable_literal)]"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use adamant_halo2::ecc::chip::constants::H;").unwrap();
    writeln!(out, "use pasta_curves::group::ff::PrimeField;").unwrap();
    writeln!(out, "use pasta_curves::pallas;").unwrap();
    writeln!(out).unwrap();
}

/// Emit the FullScalar `pub static` constants: arrays of `z`
/// values (u64) and `u` values (`[u8; 32]`).
fn write_full_scalar_table(out: &mut impl Write, zs_and_us: &[(u64, [pallas::Base; H])]) {
    writeln!(
        out,
        "/// FullScalar (NUM_WINDOWS=85) `z` values for the §7.3.1.2 R generator."
    )
    .unwrap();
    writeln!(
        out,
        "pub static R_FULL_SCALAR_Z: [u64; {}] = [",
        zs_and_us.len()
    )
    .unwrap();
    for (z, _) in zs_and_us {
        writeln!(out, "    {z},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(
        out,
        "/// FullScalar (NUM_WINDOWS=85) `u` values for the §7.3.1.2 R generator."
    )
    .unwrap();
    writeln!(out, "/// Each row: H=8 entries; each entry: 32-byte little-endian Pallas-base canonical encoding.").unwrap();
    writeln!(
        out,
        "pub static R_FULL_SCALAR_U: [[[u8; 32]; H]; {}] = [",
        zs_and_us.len()
    )
    .unwrap();
    for (_, us) in zs_and_us {
        writeln!(out, "    [").unwrap();
        for u in us {
            let repr = u.to_repr();
            write!(out, "        [").unwrap();
            for (i, byte) in repr.iter().enumerate() {
                if i == 0 {
                    write!(out, "0x{byte:02x}").unwrap();
                } else {
                    write!(out, ", 0x{byte:02x}").unwrap();
                }
            }
            writeln!(out, "],").unwrap();
        }
        writeln!(out, "    ],").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

/// Emit the ShortScalar `pub static` constants.
fn write_short_scalar_table(out: &mut impl Write, zs_and_us: &[(u64, [pallas::Base; H])]) {
    writeln!(
        out,
        "/// ShortScalar (NUM_WINDOWS_SHORT=22) `z` values for the §7.3.1.2 R generator."
    )
    .unwrap();
    writeln!(
        out,
        "pub static R_SHORT_SCALAR_Z: [u64; {}] = [",
        zs_and_us.len()
    )
    .unwrap();
    for (z, _) in zs_and_us {
        writeln!(out, "    {z},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// ShortScalar `u` values.").unwrap();
    writeln!(
        out,
        "pub static R_SHORT_SCALAR_U: [[[u8; 32]; H]; {}] = [",
        zs_and_us.len()
    )
    .unwrap();
    for (_, us) in zs_and_us {
        writeln!(out, "    [").unwrap();
        for u in us {
            let repr = u.to_repr();
            write!(out, "        [").unwrap();
            for (i, byte) in repr.iter().enumerate() {
                if i == 0 {
                    write!(out, "0x{byte:02x}").unwrap();
                } else {
                    write!(out, ", 0x{byte:02x}").unwrap();
                }
            }
            writeln!(out, "],").unwrap();
        }
        writeln!(out, "    ],").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

/// Emit a footer with cross-validation helpers.
fn write_footer(out: &mut impl Write) {
    writeln!(
        out,
        "/// Suppress unused-import warnings for code paths that"
    )
    .unwrap();
    writeln!(out, "/// only use one of the two scalar-kind tables.").unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(
        out,
        "fn _r_short_scalar_anchor() -> &'static [[u8; 32]; H] {{"
    )
    .unwrap();
    writeln!(out, "    &R_SHORT_SCALAR_U[0]").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// Helper: parse a hardcoded `[u8; 32]` byte array as a"
    )
    .unwrap();
    writeln!(
        out,
        "/// `pallas::Base` field element. Used by the `RFullScalar` /"
    )
    .unwrap();
    writeln!(out, "/// `RShortScalar` `FixedPoint::u()` impls.").unwrap();
    writeln!(out, "#[must_use]").unwrap();
    writeln!(
        out,
        "pub fn parse_pallas_base(bytes: &[u8; 32]) -> pallas::Base {{"
    )
    .unwrap();
    writeln!(
        out,
        "    pallas::Base::from_repr(*bytes).expect(\"hardcoded table u-value is in range\")"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
}
